import type { Metadata } from "next";
import { Montserrat, Kanit } from "next/font/google";
import "./globals.scss";
import Header from "@/components/layout/Header/Header";



const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["200", "300", "400", "500", "600"]
})

const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-kanit",
  weight: ["200", "300", "400", "500", "600"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${kanit.variable}`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
